### ISSUE TITLE
ある局面でbook学習をし、最善手の評価値が更新されたとき、それより前の局面の評価値が更新されない

### ISSUE THREAD

**Issue by mak-lesdis** [Nyanyan/Egaroucid#13]
edaxでいうbook fixのように、学習局面以前の局面のBookのLinkの評価値も更新する必要がある。
私は現在手動で対応しています。

**Comment by mak-lesdis** [comment]
@Nyanyan 

アプリの提供ありがとうございます！平素より便利に使わせていただいております。
Windows版アプリでBook構築をした際に気づいた点をIssueとして挙げさせていただきました。
もし管理上Issueに置きたくない場合は、Closeしてください。
よろしくお願いいたします。

**Comment by Nyanyan** [comment]
@mak-lesdis ご提案ありがとうございます。次回以降のバージョンでbook関連はデータ構造から見直す予定ですので、その際に実装しようと思います。時期はお約束できませんが、お待ちいただければ幸いです。

**Comment by mak-lesdis** [comment]
@Nyanyan 承知いたしました！ところで、開発予定の新しいbookは、今のbookと互換性は持たせる予定でしょうか？
もし互換性がなくなり1からbookを作り直す予定でしたら、一旦edaxでbook学習を進めようかと思いまして。

**Comment by Nyanyan** [comment]
@mak-lesdis 今のbookとの互換性は保つつもりですのでご安心ください。

**Comment by Nyanyan** [comment]
Edaxのbook fixはbookのlinkを再構成した後にbookのnegamaxを行うらしい。Egaroucidでも同じような感じにして、negamaxは子の読み深さ(とか読みの確率)が親の読み深さ(など)より優れている場合(つまり、親のレベル<=子のレベルでok)でのみ行うようにすると良さそう。

**Comment by Nyanyan** [comment]
book fixを実装完了
