### ISSUE TITLE
Option of using AVX-512 

### ISSUE THREAD

**Issue by Tlapesium** [Nyanyan/Egaroucid#211]
Latest AMD CPU or intel xeon series can use AVX-512.
512-bit SIMD Operation can make faster calculation of score function.

**Comment by Nyanyan** [comment]
Thank you very much for suggestion. Now I'm not considering AVX-512 optimization (because there are a lot of things I would like to implement). By some chance I'll do it, but not sure, and I'll welcome if you do it!

**Comment by okuhara** [comment]
もしご希望でしたら、AVX512 版 PR 出しますが・・。
ビルドが分かれてしまう割に、それほど高速化するわけではありませんが。

**Comment by Nyanyan** [comment]
@okuhara 返信遅れ申し訳ありません(数日間休暇でした)。

AVX512版PRぜひいただければ幸いです。私のサブPCが11世代のCore i9なので、こちらでビルド可能かと思います。また、近々GUI部分とエンジン部分で実行ファイルを分けようと考えているため、Edax+TLBのように自動でエンジンを選択するような仕様にしようと思います。そのため、(ビルドの手間は若干増えますが)ユーザ側の手間は増えない予定です。

**Comment by okuhara** [comment]
では後ほど PR 出します。
実は私は AVX512 に対応した PC は持っていません。デバッグはエミュレータ、テストは AWS EC2 で行っていますが、あまりチューニングは行えていません。
特に Skylake 世代では AVX512 は扱いにくいところがあって、下手に使うとクロックダウンが起こり、かえって遅くなることがあります。MSVC でコンパイルする場合、/arch:AVX512 でなく /arch:AVX2 /D__AVX512VL__ として intrinsic で書いたところのみ AVX512-256 を使うようにした方が速いかもしれません。gcc, clang は mprefer-vector-width=256 がデフォルトになっているので大丈夫です。

**Comment by Nyanyan** [comment]
@okuhara ありがとうございます！！少し時間がかかるかもしれないのですが、確認してマージします。

**Comment by Nyanyan** [comment]
PR #213 を出していただき、マージしました。ありがとうございました！

**Comment by okuhara** [comment]
元の Tlapesium さんの提案は評価値の集計のことだったかもしれません。もちろんそこは 512bit にすればステップは減ると思いますが、AVX10 は Intel が今後もコンシューマ製品では AVX512 はサポートしないという意思表明でもあると思いますので、ゲインが少なければあまり労力に見合わなそうな気もします。
今回の PR は 256bit ですので、おそらく AVX10 (256) でもコンパイルできると思います。

**Comment by Nyanyan** [comment]
@okuhara ありがとうございます。今後AVX10対応CPUが出たら(入手したら)実験しようと思います。
