### ISSUE TITLE
Shortcut bugs.

### ISSUE THREAD

**Issue by Eklos9z** [Nyanyan/Egaroucid#216]
Bug feedback from Optionale. 
In version 7.0.0, the undo function and the backspace shortcut key have a certain probability of causing the software to freeze, and the further into the game, the more likely it is to stutter and crash when using the undo function, which was not an issue in version 6.5.1.

**Comment by Nyanyan** [comment]
Thank you very much for bug report. I reproduced it and will fix it!

**Comment by Nyanyan** [comment]
Undo時に"フリーズする"というバグ報告

おそらくAIのヒント計算をUndo時に止める処理をしていないために起こるラグ(場合によってはフリーズのように振る舞う)だと思う。

そもそもここのifは```getData().book_information.changing == BOOK_CHANGE_NO_CELL```はundoボタンを押したとしても必ず必要だし…
https://github.com/Nyanyan/Egaroucid/blob/main/src/gui/main_scene.hpp#L500

**Comment by Nyanyan** [comment]
This bug is fixed
