### ISSUE TITLE
Hint Score Wrong Bug

### ISSUE THREAD

**Issue by Nyanyan** [Nyanyan/Egaroucid#276]
キャッシュ周りだと思うが、ヒント表示が狂う現象が報告された。Lazy SMP+TT周りが怪しいような気もするが、調査してみる。

![Screenshot 2024-07-05 190200](https://github.com/Nyanyan/Egaroucid/assets/23352688/db93aaf8-74f5-4eda-b84f-8a8d441c3846)
![Screenshot 2024-07-05 233926](https://github.com/Nyanyan/Egaroucid/assets/23352688/ec88b0b5-f0c2-45db-9a89-71b287f48c53)

ユーザ報告

**Comment by Nyanyan** [comment]
20マス空きを過ぎたあたりだけで起こるという報告をもらった。20マス空きあたりで何か変なことをしていないかを見ると良さそう

**Comment by Nyanyan** [comment]
若干挙動が怪しい棋譜例
```
c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6h7
```
![image](https://github.com/user-attachments/assets/e4a64b98-eab7-4859-9273-c3fb5e9516e3)
![image](https://github.com/user-attachments/assets/49cd4754-5b15-4ea1-83e2-09ef6238aed8)

**Comment by Nyanyan** [comment]
このバグは「以前の探索結果が残っている場合にヒント計算で起こる」という性質がある気がする。そうすると、深さ$d$@99%と$d-1$@100%(などなど)での探索を考える場合

* $d$@99%を計算し、間違ったスコアを得る
* $d-1$@100%を計算する
* 再度$d$@99%を計算するが、すでに$d$@99%の値はTTに登録されているので計算せずにTT参照だけで間違ったスコアを提示してしまう

というのが起こりそうな気がする

**Comment by Nyanyan** [comment]
いや、これはなんか違いそう

**Comment by Nyanyan** [comment]
```c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6h7g6b4a3b5g2f7f8```
![image](https://github.com/user-attachments/assets/4b72e454-98fa-4a46-9b85-f40369e4142d)
![image](https://github.com/user-attachments/assets/0d45e772-0af4-4eeb-8373-615cb3713a9b)

**Comment by Nyanyan** [comment]
```
c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6
```
この棋譜がかなりバグを再現する。低めの探索確率での読み切りから始めて自己対戦させるとこのバグが起こるらしい。
![image](https://github.com/user-attachments/assets/c309ed30-68d9-40dc-aec5-6e5fd3fd85a9)

**Comment by Nyanyan** [comment]
TTでdepthをmpc_levelよりも優先しているのは、良くないかもしれない。

**Comment by Nyanyan** [comment]
first_negascoutでのTT登録をなくしたらぱっと見バグが直ったように見える

**Comment by Nyanyan** [comment]
GUI側の問題な可能性もあるので、チェックすべき。

**Comment by Nyanyan** [comment]
tree_search_legal後に6手分くらいのTTを削除すると、Egaroucid for Consoleでもこの棋譜でバグが再現した。

> ```
> c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6
> ```
> 
> この棋譜がかなりバグを再現する。低めの探索確率での読み切りから始めて自己対戦させるとこのバグが起こるらしい。 ![image](https://private-user-images.githubusercontent.com/23352688/356552100-c309ed30-68d9-40dc-aec5-6e5fd3fd85a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMjk0NjcsIm5iZiI6MTcyMzMyOTE2NywicGF0aCI6Ii8yMzM1MjY4OC8zNTY1NTIxMDAtYzMwOWVkMzAtNjhkOS00MGRjLWFlYzUtNmU1ZmQzZmQ4NWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDIyMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDMzMTM3NmFjZTJlYzkyYWZhM2MxNWI5YWQzYTM1ODYyZjUzZDg0MTdiZTBkNDJmZjNlNjVlMmIxMDBjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSqs02BzTaHj30ToqlzliNTRq_QQD6ArhwBsKIq0c18)

**Comment by Nyanyan** [comment]
TTを全消去するとバグは起きない(TTを根近くの数手分だけ消すと起きる)ので、普通にどこか探索をミスるバグがありそう。

**Comment by Nyanyan** [comment]
nega_alpha_end_nwsを使わずに探索しても同様のバグが発生するので、中盤探索に問題がありそう

**Comment by Nyanyan** [comment]
nega_scoutからlast4を呼ぶときになぜか-last4(-beta,-alpha)と呼んでいたので修正

**Comment by Nyanyan** [comment]
nega_scout関数のみ(つまり、中盤探索の有window探索のみ)でバグがとても再現するので、ここにバグがあると見てよさそう
![image](https://github.com/user-attachments/assets/0bb7f3dc-2094-4222-9d8d-c56a9c9e4e3f)

**Comment by Nyanyan** [comment]
NegascoutでのYBWCを外したらバグが再現しなかった(たまたまかも？)ので、ここをいったん疑ってみると良いかも

**Comment by Nyanyan** [comment]
1スレッドでバグが発生する棋譜を見つけた
```
c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6h7g6b4a3b5g2f7f8c7a5b6d7e8c8g8a6e7b2h1g1d1c1a1a2d8
```

![image](https://github.com/user-attachments/assets/aac7529b-0e05-431a-8db5-49d6b0013fda)

**Comment by Nyanyan** [comment]
```
c4e3f5e6f6c5c3c6d3d2e2b3e1f4f3f2f1c2b1g3g4d6g5h4h5h3h2h6h7g6b4a3b5g2f7f8c7a5b6d7e8c8g8a6e7b2h1g1d1c1a1a2d8h8
```
も再現する

**Comment by Nyanyan** [comment]
このバグはlast4の呼び方に依存するものだった。
https://github.com/Nyanyan/Egaroucid/issues/276#issuecomment-2282662542

**Comment by Nyanyan** [comment]
NegascoutのYBWCを切るとこのケースがバグらないので、やはりNegascoutでのYBWCかなぁ
https://github.com/Nyanyan/Egaroucid/issues/276#issuecomment-2277606605

**Comment by acepck** [comment]
[lll3.txt](https://github.com/user-attachments/files/16573127/lll3.txt)
これはこの問題に関係していますか？
level 20にしてhintを2回打つと必ずf8からe7に変わります
level 22以上だと起きないかもしれません
複数スレッドで起動すると一回目からe7になるときがあります
これは7.1.0でやってますが最新のでも同じようです

**Comment by Nyanyan** [comment]
@acepck おそらく同じ問題だと思われます。

**Comment by Nyanyan** [comment]
@acepck ごめんなさい、これは違う原因のようです。
コンソール版のhintコマンドでは、指定されたヒント数が少ないときは良さそうな手にあたりをつけて探索するので、それが外れるとこのような挙動になります。
これはこれで良くないような気がするので、改善しようと思います。
https://github.com/Nyanyan/Egaroucid/issues/276#issuecomment-2282689491

**Comment by acepck** [comment]
分かりました

**Comment by Nyanyan** [comment]
nega_scout内でelderest moveを無条件にvとして扱うのがだめらしい。
g=nega_scout(elderest move)
if (v < g) ...
としないとだめみたい(こうしたらバグが消えたように見える)

**Comment by Nyanyan** [comment]
バグ修正完了！！
