### ISSUE TITLE
Evaluation Display Error Under Lower-Level AI 

### ISSUE THREAD

**Issue by venylol** [Nyanyan/Egaroucid#287]
Version: Egaroucid_7_2_0_x64_AVX512
Device Information：
![Screenshot 2024-07-25 151813](https://github.com/user-attachments/assets/6b91594c-096f-4535-82e9-be4e3089b17f)
Transcript：f5f6e6d6d7f4d3c2e3f3e2d2f2c3c4e7b3f1f8e1c1c5c6b4d1b5a5b6
Detailed Information: In this stage, when the evaluation number is adjusted to less than 35 (using 4 as an example), the evaluation display appears normal when using high-depth AI to analyze the position.
![2024_07_25_15_09_15](https://github.com/user-attachments/assets/4689d034-8a9b-49c6-81ed-f2c1608de5db)
 However, if low-depth AI is used in the same position, some very good moves are filtered out by the AI (examples of using lv4 and lv6 AI are provided below). For comparison, two additional evaluations with the evaluation number set to 35 are also included.
![2024_07_25_15_12_39](https://github.com/user-attachments/assets/6c1109e6-6cb7-4fe2-bb6e-3fb363ffc6c4)
![2024_07_25_15_12_59](https://github.com/user-attachments/assets/7c986e0f-263b-4eff-a317-0b67d126bc68)
![2024_07_25_15_13_38](https://github.com/user-attachments/assets/dcc8411d-7aca-428a-84c1-4f0bfd6373ad)
![2024_07_25_15_13_57](https://github.com/user-attachments/assets/1c6b03e7-0cc0-4f7b-8865-aee0eff38428)

**Comment by venylol** [comment]
Similarly if we use a low level of ai in this position and gradually increase the evaluation number from 4 to the maximum, the hidden move (in this case g1) will never be shown, even if a worse move would have already been shown
![2024_07_25_15_43_31](https://github.com/user-attachments/assets/69733b7a-686e-4d54-a1da-1b8f6ae95e86)
![2024_07_25_15_43_58](https://github.com/user-attachments/assets/244dae49-4219-4c89-b165-f52aab052524)

**Comment by Nyanyan** [comment]
This behavior is expected. When the number of displayed moves is small, Egaroucid gradually reduces the moves with smaller level search. You set level 4 or 6, which is too low to find the best move with small number of displayed moves. Please increase the level, or display all moves.

However, I'll mitigate this issue in the next release. Thank you for giving me an opinion!
