### ISSUE TITLE
Problems with touch panel when editing board

### ISSUE THREAD

**Issue by venylol** [Nyanyan/Egaroucid#288]
When using the EDIT BOARD function, if the user is using the mouse to control the computer, there is nothing unusual about editing the board. But if the user is using a laptop touch panel to enable the edit board function. Whenever it is turned on, there is always a black disc on the h1 position.
Here's a comparison demo video of a mouse and touch panel in use
Using the Mouse，I turned on the microphone so we could hear the voice clicking：

https://github.com/user-attachments/assets/def12c61-6efc-495f-969f-c39c60fa9ce9

 But when I use the touch panel, this is what happens：

https://github.com/user-attachments/assets/e70715f1-7daf-4a3b-af17-7a8ff159869c

Notably when my pointer is at the edge of the board when I click on the edit board option, no discs fall on h1, but when my pointer is inside the board, opening automatically generates a black disc. I think changing the position of the edit board option will solve this problem

**Comment by Nyanyan** [comment]
Thank you for reporting a bug.
This is probably because the button for the Edit Board function on the menu bar is located above h1, so when you use a touch panel it recognizes h1 as being clicked. 
I'll try to fix it in the next version, but I don't sure it can be fixed. Also, it'll be hard because I don't have a PC with touch panel. Anyway, I'll do my best.

**Comment by venylol** [comment]
> Thank you for reporting a bug. This is probably because the button for the Edit Board function on the menu bar is located above h1, so when you use a touch panel it recognizes h1 as being clicked. I'll try to fix it in the next version, but I don't sure it can be fixed. Also, it'll be hard because I don't have a PC with touch panel. Anyway, I'll do my best.

Well, from my own prospective , maybe repositioning the edit board function a little bit upwards can solve the problem , as you can see in the second vedio, At first my pointer just touched the edge of the board when I clicked on this option, and no disc appeared on h1. perhaps  making sure that the position of this edit board option does not overlap with the board behind can fix the bug

**Comment by Nyanyan** [comment]
This bug is fixed (but not tested because I don't have a computer with touch panel). Thank you very much!
