### ISSUE TITLE
screenshots naming with current transcripts

### ISSUE THREAD

**Issue by venylol** [Nyanyan/Egaroucid#289]
If possible , I would be appreciate and thankful that the program could add the option to name the screenshot as the current transcript when saving and copying  the screenshot. kind of like this 
![image](https://github.com/user-attachments/assets/7ad82000-c531-4fc3-8902-feb48c4ebf84)
And if it is not possible to export the current transcript, it goes back to the default naming by date

**Comment by Nyanyan** [comment]
Thank you very much for the suggestion. I'll add an option to save the screenshots with transcripts.
Perhaps it will be with date information, such as ```2024_07_25_2_16_57_f5d6c3.png```, is it ok?

**Comment by Nyanyan** [comment]
This function is implemented. Thank you for suggestion!
![image](https://github.com/user-attachments/assets/472e14cb-0304-42ff-a01b-029c590b1ba7)
