### ISSUE TITLE
endsearch_nws tt

### ISSUE THREAD

**Issue by acepck** [Nyanyan/Egaroucid#295]
if (tt->upper <= alpha) {
    search->undo_noeval(&move_list[move_idx].flip);
    continue;
}
全ての手がttにヒットしてここで流れてしまうと
vとして初期値の-SCORE_INFが返されてまずいような気がします
なのでcontinue;の前に
if (v < tt->upper)
    v = tt->upper;
を入れておく必要がありそうに思います

元のコードではこの場合alphaが返されるので問題なかったのですが

**Comment by Nyanyan** [comment]
ご指摘ありがとうございます。修正しました。

**Comment by acepck** [comment]
if (v < tt->upper)
これも必要なように思います
無条件で更新してしまうとより低い値で上書きしてしまった場合
それを返された上の局面がその局面を過大評価してしまうように思うのですが

**Comment by Nyanyan** [comment]
忘れていました。ありがとうございます。修正しました。若干集中力が切れているのもあり、今日はこれで寝ます。またもしお気づきの点がありましたら教えていただけると幸いです。
