### ISSUE TITLE
Flip SIMD Bug (AVX-512)

### ISSUE THREAD

**Issue by Nyanyan** [Nyanyan/Egaroucid#305]
PR #293 でいただいたflip_simdについて、AVX512版をEgaroucidのGUI版でビルドすると、うまく返る石が計算できないバグがある。コンソール版では問題ない。

具体的な挙動: https://github.com/Nyanyan/Egaroucid/pull/293#issuecomment-2287848573
> 具体的な局面をお伝えします。
> 
> 今手元で調査しているのですが、初期局面
> 
> ```
> player = 0x0000000810000000ULL
> opponent = 0x0000001008000000ULL
> ```
> 
> で`place = 19`(e8)に着手すると、返る石が`0x0000000008000c0a`と出てきます。本来は`0x0000000008000000`となるはずです。 `0x0000000008000c0a`は以下の画像で白星をつけた場所なので、縦方向と斜め(ホワイトライン)のLSB方向の計算に問題があります。 ![image](https://private-user-images.githubusercontent.com/23352688/357679492-ce213422-518f-4a7f-a8aa-991c7078f3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTExODksIm5iZiI6MTcyMzYxMDg4OSwicGF0aCI6Ii8yMzM1MjY4OC8zNTc2Nzk0OTItY2UyMTM0MjItNTE4Zi00YTdmLWE4YWEtOTkxYzcwNzhmM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA0NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTFiNWJlMzc5OGM0MTFmYTYyYTA0ZjI0ZTkzNWRmNGEwNjNmZmFiZGYyZGYwOTJiYWRiNTc3NjBhMzVmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQXB0bm3PBiGuB7xXW1cmcbjv50wuxiv6zZaNOpjsOQ)
> 
> 他にも、初期局面で`place=26`(f5)では`0xb020100` (本来は`0x8000000`)となっていました。これは水平とホワイトラインのLSB方向に問題があります。
> 
> 初期局面で`place=37`(c4)、`place=44`(d3)ではflipが0となりました。

**Comment by acepck** [comment]
[flip_simd2.txt](https://github.com/user-attachments/files/16608349/flip_simd2.txt)
やはりデータの問題かなと思ったのでそこを完全に元のコードにしてみましたが

**Comment by Nyanyan** [comment]
flip_simd2.txtでも変わらないようです…

**Comment by acepck** [comment]
だめでしたかすみません
[flip_simd3.txt](https://github.com/user-attachments/files/16610433/flip_simd3.txt)
もしお時間あったときこれで初手でplay e6と打ったときのログを教えて下さいませんか

**Comment by acepck** [comment]
[flip_simd4.txt](https://github.com/user-attachments/files/16612467/flip_simd4.txt)
やはり最初のこのコードで問題なかったようです
linuxのgccとclang、windowsのclangでも正しく動いているようなので
これで駄目ならコンパイラの問題と諦めます

**Comment by acepck** [comment]
ところでこの件とは関係なく以前から少し思っていたことなのですが
GUIバージョンのEgaroucidはclangではコンパイルできないのでしょうか？
もしできるのならそれだけで結構速くなりそうな気もしますけど

**Comment by Nyanyan** [comment]
こちらで調べてみた結果ですが、何か未定義動作を踏んでいそうな挙動でした。AVX512版のflipを以下のように左右で分割して書いて動作を見ていたところ、コメントアウトしてある```mm256_print_epu64(fl);```を実行するようにする(ただ```fl```の内部情報を出力するだけです)と、うまく動くようになりました。この関数は自作のもので、定義を貼っておきます。

これ以上の確認は結構大変そうです…(そもそもコードの内容を私が把握しきれていませんので…)

```
__m256i bp = _mm256_broadcastq_epi64(OP);
__m256i bo = _mm256_permute4x64_epi64(_mm256_castsi128_si256(OP), 0x55);
// left
__m256i ml = lrmask[place].v4[0]; // mask
__m256i ll = _mm256_andnot_si256(bo, ml); // outflank
__m256i t1 = _mm256_add_epi64(ll, _mm256_set1_epi64x(-1));
__m256i t2 = _mm256_ternarylogic_epi64(ml/*mask*/, t1, ll/*outflank*/, 0x60); // lmask
__mmask8 k0 = _mm256_test_epi64_mask(bp, t2);
__m256i fl = _mm256_maskz_andnot_epi64(k0, bp, t2);
//std::cerr << "flip4 left ";
//mm256_print_epu64(fl); // *
// right
__m256i mr = lrmask[place].v4[1]; // mask
__m256i rr = _mm256_and_si256(bp, mr);
__m256i t0 = _mm256_srlv_epi64(_mm256_set1_epi64x(-1), _mm256_lzcnt_epi64(rr));
__m256i t3 = _mm256_ternarylogic_epi64(bo, mr, rr, 0x04);
__mmask8 k1 = _mm256_cmp_epi64_mask(t3, rr, _MM_CMPINT_LT);
__m256i f4 = _mm256_mask_ternarylogic_epi64(fl, k1, t0, mr, 0xf2);
//std::cerr << "flip4 +right ";
//mm256_print_epu64(f4);
__m128i f2 = _mm_or_si128(_mm256_castsi256_si128(f4), _mm256_extracti128_si256(f4, 1));
return _mm_or_si128(f2, _mm_shuffle_epi32(f2, 0x4e));
```

```
void mm256_print_epu64(const __m256i v){
    const uint64_t* varray = (uint64_t*)&v;
    for (int i = 0; i < 4; ++i){
        std::cerr << varray[i] << " ";
    }
    std::cerr << std::endl;
}
```

**Comment by Nyanyan** [comment]
> [flip_simd4.txt](https://github.com/user-attachments/files/16612467/flip_simd4.txt)
やはり最初のこのコードで問題なかったようです
これで駄目ならコンパイラの問題と諦めます

flip_simd4もだめそうでした。何か未定義動作を踏んでいそうな挙動なのもあり、コンパイラの問題かもしれません

**Comment by Nyanyan** [comment]
> GUIバージョンのEgaroucidはclangではコンパイルできないのでしょうか？

使用しているGUIのライブラリ[Siv3D](https://siv3d.github.io/ja-jp/)が、基本的にはVisual Studioでの開発を前提としていそうなので、今のところ考えていません。ただ、clangでコンパイルできないというわけではなさそうです

**Comment by acepck** [comment]
わざわざ検証ありがとうございます
自分でぱっと見たところは副作用完了点の間に何か二回やってるようにも見えないし
どこかおかしなことやってるところがあるんでしょうか

**Comment by Nyanyan** [comment]
現時点だと全く何もわかりません…
これは時間をかけて検証してみようと思います。

**Comment by acepck** [comment]
これがやっていることは左側の場合
このパターンがあって右下に打とうとする場合
- - - - - - - -
- X - - - - - -
- - O - - - - -
- - - X - - - -
- - - - O - - -
- - - - - O - -
- - - - - - O -
- - - - - - - -

__m256i ml = lrmask[place].v4[0];
m - - - - - - -
- m - - - - - -
- - m - - - - -
- - - m - - - -
- - - - m - - -
- - - - - m - -
- - - - - - m -
- - - - - - - -
これがマスク

__m256i ll = _mm256_andnot_si256(bo, ml);
Oがあるところをmから除く
m - - - - - - -
- m - - - - - -
- - - - - - - -
- - - m - - - - 
- - - - - - - -
- - - - - - - -
- - - - - - - -
__m256i t1 = _mm256_add_epi64(ll, _mm256_set1_epi64x(-1));
llから1を引く
m - - - - - - -
- m - - - - - -
- - - - - - - -
- - - - m m m m
m m m m m m m m
m m m m m m m m
m m m m m m m m
m m m m m m m m

__m256i t2 = _mm256_ternarylogic_epi64(ml, t1, ll, 0x60);
t1とllをXORしたものとmlとのANDをとる
- - - - - - - -  t1 ^ ll
- - - - - - - -
- - - - - - - -
- - - m m m m m
m m m m m m m m
m m m m m m m m
m m m m m m m m
m m m m m m m m

- - - - - - - - (t1 ^ ll) & ml
- - - - - - - -
- - - - - - - -
- - - 2 - - - -
- - - - 2 - - -
- - - - - 2 - -
- - - - - - 2 -
- - - - - - - -
__mmask8 k0 = _mm256_test_epi64_mask(bp, t2);
Xとt2をANDして0でなかったら1 そうでなかったら0
- - - - - - - -
- - - - - - - -
- - - - - - - -
- - - X - - - -
- - - - - - - -
- - - - - - - -
- - - - - - - -
- - - - - - - -

__m256i fl = _mm256_maskz_andnot_epi64(k0, bp, t2);
k0が1だったらt2からXを除く
- - - - - - - -
- - - - - - - -
- - - - - - - -
- - - - - - - -
- - - - f - - -
- - - - - f - -
- - - - - - f -
- - - - - - - -
これが返る石

最初のパターンがこれだったら
- - - - - - - -
- X - - - - - -
- - O - - - - -
- - - - - - - -
- - - - O - - -
- - - - - O - -
- - - - - - - - (t1 ^ ll) & ml
- - - - - - - -
- - - - - - - -
- - - 2 - - - -
- - - - 2 - - -
- - - - - 2 - -
- - - - - - 2 -
- - - - - - - -
t2とXをANDしても0だからk0も0になって
__m256i fl = _mm256_maskz_andnot_epi64(k0, bp, t2);
ここでflに何も入らない
k0はこの場合64ビット単位で4つ同時にやっているので0000から1111まで15通りの値になる
1が立っているビットの所だけflに値が入る

**Comment by acepck** [comment]
何か表示がぐちゃぐちゃになったので
[u.txt](https://github.com/user-attachments/files/16615854/u.txt)

**Comment by acepck** [comment]
右側に打つ場合
[u2.txt](https://github.com/user-attachments/files/16616275/u2.txt)

**Comment by acepck** [comment]
[flip_simd5.txt](https://github.com/user-attachments/files/16621545/flip_simd5.txt)
これはどうでしょうか
inline関数でなくしたので正しく生成されるかも？
inlineでなくなった速度の低下はとくになかったです
endsearch_last_simd.hppとendsearch_nws_last_simd.hppにあるFlip::を全部取り除く必要があります

**Comment by Nyanyan** [comment]
解説ありがとうございます。大変勉強になります。
flip_simd5についても、実験してみます。

**Comment by Nyanyan** [comment]
@acepck こちらの問題について調査した結果のご報告です。
結論を言えば、こちらのビルド環境の問題でした。flip_simd4と5の両方を確認したところ、どちらも動きました。

私はCore i9-13900Kをメインで使っており、これでAVX512版もビルドしていました(Visual Studioでエラーも出ずでき、これまではこれで問題ありませんでした)。ただ、以前PRいただいたAVX512版はCore i9-13900Kでビルドしたものだとうまく動きませんでした。そこで、Core i9-11900Kでビルドしてみると、うまく動きました。13900KはEコアでAVX-512が動かないはずで、その関係でビルドが実はうまくいっていなかったようです。

大変お騒がせしました。たくさん助言いただきありがとうございました。これで問題が解決しましたので、flip_simd4を改めて採用させていただきます。
次回のリリースからは、AVX-512が動くCPUでビルドするようにします。

**Comment by okuhara** [comment]
> ところでこの件とは関係なく以前から少し思っていたことなのですが GUIバージョンのEgaroucidはclangではコンパイルできないのでしょうか？ もしできるのならそれだけで結構速くなりそうな気もしますけど

横からすみません。このバグとは関係ないのですが、edax-AVX は gcc, clang, msvc, icc の比較では clang が一番遅いです。
その原因と思われるのがこの flip の部分で、最適化しようとしてかえって悪くしているような感じでした。
ですのでうまく書き換えると clang のスコアはもう少しよくなるかもしれないと思っていました。
私も acepck さんのコード、参考にさせていただきます。

MSVC で正しく動作しない AVX512 のソース、私も持っています。あまり速くないバージョンだったので、気にしませんでしたが。

**Comment by acepck** [comment]
okuharaさんどうも
2020年頃edax-AVXのコードを見ていて一つにまとめられているflip関数を見つけて
最初は遊びで作った関数だろうと思ったんです(相当昔からマス毎に作るものと思いこんでいたので)
でも試しにslarinに組み込んで動かしてみたら中盤に関してはかなり速くなったので
驚いてすぐに一つのバージョンを作ったんです
なのであれを知らなかったら未だに遅い分割バージョンを使っていたはずです

**Comment by Nyanyan** [comment]
> MSVC で正しく動作しない AVX512 のソース、私も持っています。あまり速くないバージョンだったので、気にしませんでしたが。

情報ありがとうございます。この情報もあり、AVX512版でacepckさんのコードが動かないのはMSVCのバグという方針で結論づけようかと思います。

ただ、詳しくflip_simd4について調査してみると、GUI版(Visual StudioでSiv3DのプロジェクトとしてMSVCでコンパイル)はバグが発生するものの、コンソール版をVisual Studioのコンソールアプリとしてビルドするとうまく動くという現象が発生しました。この部分をもう少し調査していこうと思いますので、もしかしたらこの件について今後進展があるかもしれません。

**Comment by Nyanyan** [comment]
最終的には、MSVCについてはokuharaさんのコード、他のコンパイラではそれぞれ性能を計測してみて、性能が良いコードを使うといった使い分けをしようかとも思っています。
flip単体での性能をきちんと計測するため、[perft](https://aartbik.blogspot.com/2009/02/perft-for-reversi.html)で実験しようと思います。

**Comment by okuhara** [comment]
@acepck さん
コード拝見しました。いくつもの最適化の工夫、まだこれほど改善の余地があったかと感服しました。
edax-AVX にも取り込ませていただくとともに、私の [bitboard の解説ページ](http://www.amy.hi-ho.ne.jp/okuhara/bitboard.htm)にも加えさせていただきたいと思います。
acepck さんをメンションするときにリンクすべき url があれば教えてください。無ければこの PR にリンクします。

**Comment by acepck** [comment]
こちらも色々勉強になっています
サイトは特にないのでそれでお願いします

**Comment by acepck** [comment]
avx2バージョンは去年だったか試したときokuharaさんのバージョンの方が速かったのですが
こないだEgaroucidでやってみたら逆転していてそのPRにも入れておいたんですが
今改めてslarinで両方試すとokuharaさんのバージョンの方がはっきり速いですね
確かそのとき-march=nativeで作ってしまっていてslarinのバージョンの方がavx512を使えたときにだけ
若干速くなってしまっていたようです
実際意味があるhaswellに制限するとやっぱりokuharaさんのバージョンの方が速かったということだったようです

**Comment by okuhara** [comment]
@acepck さん
コンパイルされたコードを見たときはいけそうな気がしたのですが、Haswell で測定すると確かに元のコードの方が速いですね。PCMPGTQ が latency = 5 と劇遅なのが響いているようです。
CPU によっては逆転する可能性はありますが、本線では採用しにくいかもしれません。

**Comment by Nyanyan** [comment]
お二人とも、大変ありがとうございました。先日いただいたプルリクエスト #320 を元に、acepckさんのアイデアと元のコードとで、コンパイラごとに最適と思われる組み合わせとなるようにしました。
なお、もともとこのissueで議論していたAVX512版のバグですが、やはりMSVCのバグだと思われます。

最終的なコードは以下の通りとなりました。
SIMD版のコード: https://github.com/Nyanyan/Egaroucid/blob/bcb1ad2437668d3727815f923e663a159976492b/src/engine/flip_simd.hpp
AVX512版のコード: https://github.com/Nyanyan/Egaroucid/blob/bcb1ad2437668d3727815f923e663a159976492b/src/engine/flip_avx512.hpp

改めて、ご協力大変ありがとうございました。今後ともどうぞよろしくお願いいたします。
