### ISSUE TITLE
Add an option to delete games in the imported games list

### ISSUE THREAD

**Issue by venylol** [Nyanyan/Egaroucid#349]
If possible, I would appreciate it if you could add a option to delete single games in the imported games list. This would make it much more convenient for me to review and organize games later. Thank you very much!LoL
![image](https://github.com/user-attachments/assets/182d5778-538b-4798-b018-19d3316ef7e6)

**Comment by Nyanyan** [comment]
@venylol I'll add delete option in the next version!
Thank you very much for contacting me!

**Comment by Nyanyan** [comment]
方針
- GUI側は各項目の左上にバツ印を付けて、これで消せるようにする
- 内部的には、バツ印を押された対局のインデックスを取得→保存日時情報(=jsonファイル名)を取得→csvとjsonを削除

**Comment by Nyanyan** [comment]
画面デザインはこんな感じになった
![image](https://github.com/user-attachments/assets/dec24a7f-44f3-457b-88cd-0eb9567e35b1)

**Comment by Nyanyan** [comment]
画像をボタンとして扱うコードを書いておいたほうが良さそう

**Comment by Nyanyan** [comment]
実装完了
ついでに取り込みボタンの角丸の半径を若干大きくした
![image](https://github.com/user-attachments/assets/f2b4eec7-5388-457f-b59d-a6431e0267cb)

**Comment by Nyanyan** [comment]
@venylol I've implemented an option to delete games! In the next release (version 7.5.0), you can use it! Thank you for requesting a feature!
![image](https://github.com/user-attachments/assets/6db4169b-29d8-4f87-b465-0074cc17cc47)
