### ISSUE TITLE
c++ std::max

### ISSUE THREAD

**Issue by acepck** [Nyanyan/Egaroucid#395]
先程コンパイルするときにエラーが出ていたので一応
src/engine/time_management.hppの78行目とsrc/engine/ai.hppの730行目で
std::maxの二つの引数の型が違うと言われてました
linuxではuint64_tの型がunsigned long longではなくunsigned longなので1ULLとかだと駄目らしいです
```
return std::max(static_cast<decltype(remaining_time_msec_margin)>(1), remaining_time_msec_margin / remaining_moves_proc);
return std::max<uint64_t>(1, remaining_time_msec_margin / remaining_moves_proc);
```
1ULとかにしてコンパイルしましたがこんな感じにする必要があるのかもしれません

**Comment by Nyanyan** [comment]
ご報告ありがとうございます。
```
return std::max<uint64_t>(1, remaining_time_msec_margin / remaining_moves_proc);
```
こちらの書き方で統一しました。
こちらでも後でUbuntu機を使って検証します。

**Comment by Nyanyan** [comment]
手元のUbuntu機+g++でチェック完了しました。ありがとうございました。
