### ISSUE TITLE
end_evaluate Optimization

### ISSUE THREAD

**Issue by Nyanyan** [Nyanyan/Egaroucid#48]
```end_evaluate```と```end_evaluate_odd```の条件分岐をなくしたい。

```end_evaluate_odd```は符号ビットをうまく使うとできそう。
```end_evaluate```は符号ビットに加えて引き分け処理を書かなければいけないので大変そう

**Comment by Nyanyan** [comment]
実装済

わざわざ符号bitを見るまでもなく、```S=2P-E```として、```(S>>5)&2-1```などを使えば符号を生成できる。

**Comment by okuhara** [comment]
主要なコンパイラでの変更前、変更後のコードの比較です。
https://godbolt.org/z/54T4W9Pjc
変更前のものでもすべてのコンパイラが分岐なしのコードに落としていることがわかります。
さらに驚いたことに、すべてのコンパイラが diff が 0 にならないことを見抜き、diff == 0 の比較を省略しています。
つまりインライン展開された場合には、奇数空きではこの比較は行われません。
この部分について言えば、わかりやすい方がよいので、私は元のコードを採用しました。

**Comment by Nyanyan** [comment]
@okuhara 人間が明示的に書かなくてもうまくコンパイラが分岐や無駄な処理ををなくしてくれるのですね、驚きです。
Egaroucidでどちらを採用するかは検討します
