### ISSUE TITLE
book.egbkやeval.egevの参照位置をカレントディレクトリではなく固定にしたい

### ISSUE THREAD

**Issue by Cj-bc** [Nyanyan/Egaroucid#5]
# 概要
プログラムでそれらのファイルを読み込む際、現在の実装では「カレントディレクトリに存在する `resources/book.egbk` `resources/eval.egev` を読む」ようになっているようですが、これを

+ 実行可能ファイルと同じディレクトリに存在する `resources/book.egbk` `resources/eval.egev` or
+ 固定パスから読み込む

ように変更したいです

# 動機
archlinux用のパッケージを作成している間に問題に気が付きました。
現在の実装では、カレントディレクトリが実行可能ファイルと別のディレクトリな時に実行しようとするとコケます。

``` sh
$ cd ~
$ which Egaroucid_for_console
/usr/bin/Egaroucid_for_console
$ Egaroucid_for_console
[ERROR] can't open hash25.eghs
[ERROR] can't get hash. you can ignore this error
[ERROR] [FATAL] can't open eval resources/eval.egev
```

そして、GNU/Linuxでインストールをしたコマンドを使用する際はカレントディレクトリが異なるのが普通なので、毎回見付けられずに結果として毎回手動でコマンドライン引数を用いる必要があります。
勿論パッケージ化する際にパッチを当てることは出来ますが、他のパッケージマネージャーに対応させようとした時も同じパッチを当てる必要が出てくると思われるため、本家側で対処出来ればなと思っています。

# 固定パスの場合の具体的な提案

固定パスとする際、archlinuxでは 実行可能ファイルは `/usr/bin/`, アプリケーションから利用するデータは `/usr/share/<package-name>/` に保存するのが一般的です。これはGNU/Linux的には行儀が良いですが、ディレクトリの構造が異なるパッケージそれぞれに対して別のパスを指定する必要が出てきます。(例えばWindowsとGNU/Linuxとで別の値にする必要がある、とか...)

若しくは、その構造に従うのが難しい場合は実行可能ファイルを含む全てを `/opt/<package-name>/` に配置することも出来ます。こうする場合は、完全な絶対パスを使うのではなく「実行可能ファイルからの相対パス」として指定することとなるため、異なる環境であっても変更をせずにそのまま扱うことが出来ます。

**Comment by Nyanyan** [comment]
> 「実行可能ファイルからの相対パス」として指定する

この方針で実装してみました。
こちらのコミットで対応したつもりです。確認お願いします。
https://github.com/Nyanyan/Egaroucid/tree/22cb8d1ee743774dc0f9ac7e8e8aeb659827c597

**Comment by Cj-bc** [comment]
ありがとうございます。手元で試してみたところ、 `argv[0]` からだと上手く取れていないようです。
以下のプリントデバッグを入れてみた所、

```diff
diff --git a/src/Egaroucid_console.cpp b/src/Egaroucid_console.cpp
index c6689488..fe23bc6d 100644
--- a/src/Egaroucid_console.cpp
+++ b/src/Egaroucid_console.cpp
@@ -49,6 +49,7 @@ std::string get_binary_path(char* argv0){
 
 int main(int argc, char* argv[]){
     State state;
+    std::cout << "current argv0: <" << argv[0] << ">" << std::endl;
     std::string binary_path = get_binary_path(argv[0]);
     std::vector<Commandline_option> commandline_options = get_commandline_options(argc, argv);
     Options options = get_options(commandline_options, binary_path);
diff --git a/src/console/option.hpp b/src/console/option.hpp
index 2c5324ea..1cfde8b5 100644
--- a/src/console/option.hpp
+++ b/src/console/option.hpp
@@ -100,5 +100,8 @@ Options get_options(std::vector<Commandline_option> commandline_options, std::st
     }
     res.gtp = find_commandline_option(commandline_options, ID_GTP) == OPTION_FOUND;
     res.quiet = find_commandline_option(commandline_options, ID_QUIET) == OPTION_FOUND;
+    std::cout << res.binary_path << std::endl;
+    std::cout << res.eval_file << std::endl;
+    std::cout << res.book_file << std::endl;
     return res;
 }
```
下記のようになりました
```
$ cd ~ && Egaroucid_for_console
current argv0: <Egaroucid_for_console>

resources/eval.egev
resources/book.egbk
[ERROR] can't open hash25.eghs
[ERROR] can't get hash. you can ignore this error
[ERROR] [FATAL] can't open eval resources/eval.egev
```

**Comment by Nyanyan** [comment]
確認ありがとうございます。パスを通してある場合はargv[0]使えなさそうですね…他の策を考えます。

**Comment by Cj-bc** [comment]
軽く調べたところ、クロスプラットフォームな解決策としてはboostを使うのが手っ取り早いようです

+ [boost::dll::program_location](https://www.boost.org/doc/libs/1_81_0/doc/html/boost/dll/program_location.html)

あとは、Linuxなら ~/proc/self/exe~ が実行中のプロセスの実行ファイルへのシンボリックリンクらしいので、それを参照することもできるようです（[参考](https://stackoverflow.com/a/63229171))

手元でも確認できました:

```cpp
#include <filesystem>
std::filesystem::canonical("/proc/self/exe")
```

Windowsだと [GetModuleFileNameA](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea) とかでとれるぽいですね、こちらは試せてないです


https://stackoverflow.com/questions/1528298/get-path-of-executable

**Comment by Nyanyan** [comment]
ありがとうございます。とりあえず/proc/self/exe/を使って手元のUbuntuで動作確認が取れたので報告します。
Linux向けはこれで多分動くと思います。
https://github.com/Nyanyan/Egaroucid/tree/9f647fc797132ba42b411cf41507f4f44186172a

**Comment by Cj-bc** [comment]
こちら下記環境で、 `book.egbk` `eval.egev` 共にきちんと読み込まれることを確認しました。大丈夫そうです

```
$ uname -r
6.0.12-arch1-1-surface
$ g++ --version
g++ (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Nyanyan** [comment]
ありがとうございました！
