### ISSUE TITLE
対戦ページの表示バグ

### ISSUE THREAD

**Issue by jj1guj** [Nyanyan/Egaroucid#59]
iPhone SE2 + BraveでEgaroucidの対戦ページにアクセスすると以下の画像のように一部罫線が表示されていないように見えます。
一応拡大するとかすかに罫線が見えるので太さの設定を間違えている可能性が高そうです
![IMG_1897](https://github.com/Nyanyan/Egaroucid/assets/57407826/04b618d9-427c-4464-b25e-ffb50cabfb07)

**Comment by Nyanyan** [comment]
@jj1guj ご報告ありがとうございます。多分罫線が細すぎることで一部の環境でこうなっているようです。罫線の太さを変えてみました。ご確認お願いします。
(デプロイ後に確認してみたら少し太すぎる気がしなくはないのですが、これはこれで良い気がしたので、そちらの環境で大丈夫ならこれでいきます)

**Comment by jj1guj** [comment]
ご対応ありがとうございます！
極太にはなっていますが問題なさそうです！
