### ISSUE TITLE
The relation strength of web version. 

### ISSUE THREAD

**Issue by CGLemon** [Nyanyan/Egaroucid#73]
The web version is good and beautiful. Recently, I am checking my program and test the performance via web version. Is any relation strength of web version? For example, the Level X achieves super human, or level K achieves some other old engines.

I have another question. Because my engine is based on deep learning. Your engine is based on alpha-beta. The suitable devices of DL and alpha-beta engines are different. How do I set a "FAIR" benchmark?

Thanks!

**Comment by Nyanyan** [comment]
@CGLemon Thank you for using my program, and I'm very interested in your program. Is there a web page that I can play with your Othello AI?

The strength of web version is not thoroughly investigated. But for Egaroucid and Egaroucid for Console (both have the same engine), I published the results of battles against Edax: https://www.egaroucid.nyanyan.dev/en/technology/benchmarks/6_4_0/ , this might be helpful.

I guess you are using PV-MCTS (like AlphaZero), and I think actually there is no "FAIR" benchmark. But in Shogi AI (Japanese Chess), there is an interesting competition, "Hardware Unification Battles": https://denryu-sen.jp/hd1/index.html . In this competition, all participants use same machine, Core i9 12900K + GeForce RTX 3090 + DDR5 128GB Memory + 1TB SSD. Shogi AI players told me this competition. Another Shogi AI player said that using similar priced CPU and GPU will bring the fair tournaments.

[XOT](https://berg.earthlingz.de/xot/aboutxot.php?lang=en) is also useful if you set many battles in Othello. I used XOT in battles against Edax. The text below is taken from the benchmark page.
> If I set the game from the very beginning, same line appears a lot. To avoid this, I set the game from many different near-draw lines.

Thanks!

**Comment by CGLemon** [comment]
Thanks for answering.

I am confused about the level. The performance page says Egaroucid is slightly better than Edax under the same level. What does the level mean? I don't understand the relation strength of level. If you can get me some examples, it is good for me.

This is my current [othello](https://github.com/CGLemon/Sayuri/tree/othello) branch. The origin version is Go so I should check the correctness and remove the useless part. Weight can be found [here](https://drive.google.com/drive/folders/1E9--f5w3fIpccE6qPSqHiyGnmetINmfB?usp=drive_link). You can play with engine via GoGui. Command is....

```
$ ./Sayuri -t 1 -b 1 -p 400 -w path/to/weights
```

**Comment by Nyanyan** [comment]
@CGLemon 
The level is determined by:
* the lookahead depth
* the search probability (Multi-ProbCut (Chess Programming Wiki: https://www.chessprogramming.org/ProbCut))

You can see this area in Egaroucid (GUI version), or type ```Egaroucid_for_Console.exe -levelinfo``` in Egaroucid for Console.
![image](https://github.com/Nyanyan/Egaroucid/assets/23352688/6de44e36-6886-4662-b901-76e5ce3dfcd6)
![image](https://github.com/Nyanyan/Egaroucid/assets/23352688/7464c9f6-c50a-4768-9711-6a89bbc4f1f2)


Thank you for introducing your Sayuri. I successfully built it and using GoGUI, I had a battle between Sayuri with ```swa-s592000.bin.txt``` (white) and Egaroucid 6.4.0 (black).
![image](https://github.com/Nyanyan/Egaroucid/assets/23352688/3cb1ed5a-76c9-4830-98b0-0f95d6aa3004)

**Comment by CGLemon** [comment]
Mm…. thanks! Looks the othello branch works well.

I am curious whether it is possible that the DL based engine can beat the alpha-beta based engine. I heard a team won one game against an alpha-beta based engine which may be one of strongest engine in the world at the last ICGA cup. The team used AlphaZero technology.

After hearing the information, I decided to do the same work. But I still doubt the results. Any idea? Did you hear the similar results?

**Comment by Nyanyan** [comment]
@CGLemon Actually I tried AlphaZero-like algorithm before at [CodinGame Othello](https://www.codingame.com/multiplayer/bot-programming/othello-1), but I couldn't make it very strong. There may be a way to develop very strong engine with AlphaZero (or MCTS family), but no one discovered it.

I know an Othello AI with AlphaZero-like engine, [OLIVAW](https://arxiv.org/abs/2103.17228). This paper says that OLIVAW is stronger than Edax, but no source code available (I could not find. If you find it, I will be very pleased if you let me know.).
