### ISSUE TITLE
Graph bug

### ISSUE THREAD

**Issue by Eklos9z** [Nyanyan/Egaroucid#84]
`f5f6f7g7h7h8e6h6g6g5h5h4g8f8d3g4h3h2g3f4d7e7d8e8d6c8b8c4b5b4b3a6b6c6b7a8a4d2b2b1c2e2f1f2f3g2h1e1e3c1d1a1c3a5c7`

![{87E68357-8CC1-466d-8A74-2FD64DBA54BA}](https://github.com/Nyanyan/Egaroucid/assets/104120183/fc7f31f0-02cd-47b0-8c15-900e8e892ecc)

Every steps are -64 after G6, but it does not work on the graph.

**Comment by Nyanyan** [comment]
@Eklos9z Thank you for reporting bug. I tested the transcript and succeeded to reproduce it. I'll check what went wrong, but I'm busy in this November, so it can take long.

**Comment by Nyanyan** [comment]
@Eklos9z This bug is fixed in this commit!: https://github.com/Nyanyan/Egaroucid/commit/62d215f087e98235b14722ebb32c2f6062a37aa4
Thank you for reporting bug!
